// GTA-style vehicle makes and models for the towing system
export const GTA_VEHICLE_MAKES = [
  'Albany',
  'Annis',
  'Benefactor',
  'BF',
  'Bravado',
  'Brute',
  'Buckingham',
  'Canis',
  'Cheval',
  'Coil',
  'Declasse',
  'Dewbauchee',
  'Dinka',
  'Dundreary',
  'Emperor',
  'Enus',
  'Fathom',
  'Gallivanter',
  'Grotti',
  'HVY',
  'Imponte',
  'Invetero',
  'Jobuilt',
  'Karin',
  'Lampadati',
  'Maibatsu',
  'Mammoth',
  'Maxwell',
  'MTL',
  'Obey',
  'Ocelot',
  'Overflod',
  'Pegassi',
  'Pfister',
  'Principe',
  'Progen',
  'Schyster',
  'Shitzu',
  'Stanley',
  'Truffade',
  'Ubermacht',
  'Vapid',
  'Vulcar',
  'Weeny',
  'Western',
  'Willard',
  'Zirconium',
] as const;

export const GTA_VEHICLE_MODELS: Record<string, string[]> = {
  Albany: ['Alpha', 'Buccaneer', 'Cavalcade', 'Emperor', 'Esperanto', 'Hermes', 'Manana', 'Primo', 'Roosevelt', 'Virgo', 'Washington'],
  Annis: ['Elegy RH8', 'Elegy Retro Custom', 'RE-7B', 'S80RR', 'Savestra', 'ZR350'],
  Benefactor: ['Dubsta', 'Feltzer', 'Glendale', 'Krieger', 'Panto', 'Schafter', 'Schwartzer', 'Serrano', 'Stirling GT', 'Streiter', 'Surano', 'XLS'],
  BF: ['Bifta', 'Club', 'Dune Buggy', 'Injection', 'Raptor', 'Surfer', 'Weevil'],
  Bravado: ['Banshee', 'Bison', 'Buffalo', 'Duneloader', 'Gauntlet', 'Gresley', 'Greenwood', 'Half-track', 'Paradise', 'Rat-Loader', 'Rumpo', 'Verlierer', 'Youga'],
  Brute: ['Boxville', 'Bus', 'Camper', 'Dashound', 'Pony', 'Rental Shuttle Bus', 'Stockade', 'Tipper', 'Utility Truck'],
  Canis: ['Bodhi', 'Crusader', 'Freecrawler', 'Kalahari', 'Kamacho', 'Mesa', 'Seminole', 'Seminole Frontier'],
  Cheval: ['Fugitive', 'Marshall', 'Picador', 'Surge', 'Taipan'],
  Coil: ['Brawler', 'Cyclone', 'Raiden', 'Rocket Voltic', 'Voltic'],
  Declasse: ['Asea', 'Burrito', 'Drift Tampa', 'Drafter', 'Gang Burrito', 'Granger', 'Impaler', 'Lifeguard', 'Mamba', 'Moonbeam', 'Rancher XL', 'Rhapsody', 'Sabre Turbo', 'Stallion', 'Tampa', 'Tornado', 'Tulip', 'Vamos', 'Vigero', 'Voodoo', 'Yosemite'],
  Dewbauchee: ['Exemplar', 'JB 700', 'Massacro', 'Rapid GT', 'Seven-70', 'Specter', 'Vagner'],
  Dinka: ['Akuma', 'Blista', 'Double-T', 'Enduro', 'Jester', 'Kanjo', 'Thrust', 'Vindicator', 'Veto Classic', 'Veto Modern'],
  Dundreary: ['Landstalker', 'Regina', 'Stretch', 'Virgo Classic'],
  Emperor: ['ETR1', 'Habanero'],
  Enus: ['Cognoscenti', 'Deity', 'Huntley S', 'Jubilee', 'Paragon R', 'Stafford', 'Super Diamond', 'Windsor'],
  Gallivanter: ['Baller'],
  Grotti: ['Bestia GTS', 'Brioso R/A', 'Carbonizzare', 'Cheetah', 'Cheetah Classic', 'Furia', 'GT500', 'Itali GTO', 'Stinger', 'Stinger GT', 'Turismo Classic', 'Turismo R', 'Visione', 'X80 Proto'],
  HVY: ['Airtug', 'Barracks', 'Brickade', 'Chernobog', 'Cutter', 'Dock Handler', 'Dozer', 'Dump', 'Insurgent', 'Menacer', 'Mixer', 'Scarab', 'Nightshark'],
  Imponte: ['Beater Dukes', 'Deluxo', 'Duke O\'Death', 'Dukes', 'Nightshade', 'Phoenix', 'Ruiner'],
  Invetero: ['Coquette', 'Coquette BlackFin', 'Coquette Classic'],
  Karin: ['190z', 'Asterope', 'BeeJay XL', 'Calico GTF', 'Dilettante', 'Everon', 'Futo', 'Futo GTX', 'Intruder', 'Kuruma', 'Rebel', 'Sultan', 'Sultan RS', 'Technical'],
  Lampadati: ['Casco', 'Felon', 'Felon GT', 'Furore GT', 'Komoda', 'Novak', 'Pigalle', 'Tropos Rallye', 'Viseris'],
  Maibatsu: ['Mule', 'Penumbra', 'Penumbra FF', 'Sanchez', 'Manchez', 'Manchez Scout'],
  Mammoth: ['Hydra', 'Patriot', 'Patriot Mil-Spec', 'Patriot Stretch', 'Squaddie', 'Thruster', 'Tula'],
  Maxwell: ['Asbo', 'Vagrant'],
  MTL: ['Brickade 6x6', 'Cerberus', 'Dune', 'Flatbed', 'Packer', 'Pounder', 'Fire Truck'],
  Obey: ['8F Drafter', '9F', 'Omnis', 'Rocoto', 'Tailgater', 'Tailgater S'],
  Ocelot: ['Ardent', 'F620', 'Jugular', 'Locust', 'Lynx', 'Pariah', 'Penetrator', 'R88', 'Stromberg', 'Swinger', 'Virtue', 'XA-21'],
  Overflod: ['Autarch', 'Entity XF', 'Entity XXR', 'Imorgon', 'Tyrant'],
  Pegassi: ['Bati 801', 'Esskey', 'FCR 1000', 'Faggio', 'Infernus', 'Infernus Classic', 'Monroe', 'Oppressor', 'Osiris', 'Reaper', 'Ruffian', 'Tempesta', 'Tezeract', 'Torero', 'Torero XO', 'Toreador', 'Vacca', 'Vortex', 'Zentorno', 'Zorrusso'],
  Pfister: ['811', 'Comet', 'Comet Retro Custom', 'Comet S2', 'Comet Safari', 'Comet SR', 'Growler', 'Neon'],
  Principe: ['Deveste Eight', 'Diabolus', 'Lectro', 'Nemesis'],
  Progen: ['Emerus', 'GP1', 'Itali GTB', 'PR4', 'T20', 'Tyrus'],
  Schyster: ['Deviant', 'Fusilade'],
  Truffade: ['Adder', 'Nero', 'Nero Custom', 'Thrax', 'Z-Type'],
  Ubermacht: ['Oracle', 'Oracle XS', 'Rebla GTS', 'SC1', 'Sentinel', 'Sentinel Classic', 'Zion', 'Zion Classic'],
  Vapid: ['Benson', 'Blade', 'Bobcat XL', 'Bullet', 'Caracara', 'Clique', 'Contender', 'Dominator', 'Dominator ASP', 'Dominator GTT', 'Dominator GTX', 'Ellie', 'Flash GT', 'FMJ', 'GB200', 'Guardian', 'Hotknife', 'Hustler', 'Minivan', 'Monster', 'Peyote', 'Retinue', 'Riata', 'Sadler', 'Sandking', 'Slamvan', 'Speedo', 'Stanier', 'Tow Truck', 'Trophy Truck', 'Winky'],
  Vulcar: ['Fagaloa', 'Ingot', 'Nebula Turbo', 'Warrener', 'Warrener HKR'],
  Weeny: ['Dynasty', 'Issi', 'Issi Classic', 'Issi Sport'],
  Western: ['Bagger', 'Cliffhanger', 'Daemon', 'Gargoyle', 'Nightblade', 'Rat Bike', 'Reever', 'Rampant Rocket', 'Seashark', 'Sovereign', 'Zombie Bobber', 'Zombie Chopper'],
  Willard: ['Faction', 'Faction Custom'],
  Zirconium: ['Journey', 'Stratum'],
};

export const getModelsForMake = (make: string): string[] => {
  return GTA_VEHICLE_MODELS[make] || [];
};

export const TOW_REASONS = [
  'Vehicle Breakdown',
  'Accident Recovery',
  'Illegal Parking',
  'Abandoned Vehicle',
  'Police Impound',
  'Expired Registration',
  'Owner Request',
  'Repo Order',
  'Traffic Obstruction',
  'Evidence Seizure',
  'DUI Arrest',
  'Warrant/Arrest',
  'Other',
] as const;

export const LS_LOCATIONS = [
  'Vinewood Hills',
  'Del Perro Pier',
  'Vespucci Beach',
  'Downtown Los Santos',
  'Little Seoul',
  'Pillbox Hill',
  'Legion Square',
  'Mission Row',
  'La Mesa',
  'El Burro Heights',
  'Cypress Flats',
  'East Los Santos',
  'Strawberry',
  'Davis',
  'Chamberlain Hills',
  'Grove Street',
  'Rancho',
  'Mirror Park',
  'East Vinewood',
  'Rockford Hills',
  'Morningwood',
  'Pacific Bluffs',
  'Richman',
  'Richman Glen',
  'Tongva Hills',
  'Great Chaparral',
  'Sandy Shores',
  'Grapeseed',
  'Paleto Bay',
  'Mount Chiliad',
  'Chumash',
  'Banham Canyon',
  'Harmony',
  'Grand Senora Desert',
  'Route 68',
  'Lago Zancudo',
  'Fort Zancudo',
  'LSIA',
  'Elysian Island',
  'Terminal',
  'Port of Los Santos',
  'Maze Bank Arena',
  'Olympic Freeway',
  'La Puerta Freeway',
  'Del Perro Freeway',
  'Great Ocean Highway',
  'Senora Freeway',
] as const;
